name: hello-world
on: push
env:
  docker_username: ${{ github.actor }}
  docker_password: ${{ secrets.GITHUB_TOKEN }}
  GIT_COMMIT: ${{ github.sha }}
jobs:
  Build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 
      - name: Build application 
        run: chmod +x ci/build-app.sh && ci/build-app.sh
      - name: Test application
        run: chmod +x ci/unit-test-app.sh && ci/unit-test-app.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with: 
          name: code
          path: .
  Docker-image:
    runs-on: ubuntu-latest
    needs: [Build]
    permissions:
      packages: write
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: code
          path: .
      - name: Build docker image
        run: chmod +x ci/build-docker.sh && ci/build-docker.sh
      - name: Push docker image
        run: chmod +x ci/push-docker.sh && ci/push-docker.sh